import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {
          // Deliberately a plain, synchronous <script> tag rather than
          // next/script's <Script strategy="beforeInteractive">. Next's
          // Script component defers loading through an internal queue
          // (self.__next_s) that doesn't reliably execute for plain static
          // assets in this dev setup — a real script tag executes in
          // document order exactly as the Go WASM runtime expects, with no
          // Next-specific timing involved.
        }
        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script src="/wasm_exec.js"></script>
        {children}
      </body>
    </html>
  );
}